#!/bin/awk -f
# This script gets the number of particles lost after 1 turn
# it should be called as $ ./getlppt trackSTART trackloss
BEGIN { FS=" ";
    IGNORECASE=1; 
#    print "  getting data from files...";
}
{
    if($1!~/^(@*$)/){#header in first file
	print "start, x="$1",px="$2",y="$3",py="$4",t="$5",pt="$6";" >> ("madxInrays.madx");
    }
}
END { 
}
