#!/bin/sh -f
# This script runs particles 



echo "HI THERE ! This script runs particles through out"
echo "  an accelerator with fixed target to optimize the dynamic apperture"
echo "  authors: oblancog, collamati."

# Number of turns
#: ${ngiri:="1"}

echo "NOW..."
echo "Checking soft. requirements :"
echo "  Checking for root ..."
hash root 2>/dev/null || { echo >&2 "OOOps... I require root but it's not installed.  Aborting."; exit 1; }
echo "    ... root found"
echo "  Checking for awk ..."
hash awk 2>/dev/null || { echo >&2 "OOOps... I require awk but it's not installed.  Aborting."; exit 1; }
echo "    ... akw found"
echo "  Checking for madx ..."
hash madx 2>/dev/null || { echo >&2 "OOOps... I require madx but it's not installed.  Aborting."; exit 1; }
echo "    ... madx found"
echo "  Checking for python ..."
hash python 2>/dev/null || { echo >&2 "OOOps... I require madx but it's not installed.  Aborting."; exit 1; }
echo "    ... python found"
echo "ALL SOFTWARE requirements are OK..."

echo "creating twiss for list of s positions to check"
#madx < job.twiss.madx | grep -i warning
madx < job.twiss.madx > /dev/null 2>&1

# Optimization run loop
rm -f matchelements.madx current_maxEaccept.madx match.log
madx < job.opt.madx

echo "FINALLY DONE. Adios"
